// Public content and routes sourced from the existing Classic portfolio.
export const projects=[['Finfold','/finfold'],['Signals Notebook','/signals'],['CollovGPT','/collov'],['Ctrip Hotel','/ctrip'],['UnifyUX','/unifyux'],['ID.AURA','/vw-id-aura/'],['CALL ME YAO 妖','/yao'],['Bill Vampire','/billvampire'],['WeNeed','/weneed'],['Crypto Copilot','/cryptocopilot'],['Narrative Card RPG','/pleasurecontract'],['Borrowed Light','/borrowedlight']];
export const tracks=[['3428817825','霓虹梦境 · Neon Dream','Original / 原创'],['3428818648','丝电回路 · Silk Circuit','Original / 原创'],['3413956825','招安不是上岸','2026'],['3413978040','사상 최고가의 여름','2026'],['1873346292','逍遥叹','Cover / 翻唱'],['1969608391','Right Here Waiting For You','Cover / 翻唱'],['2746338489',"Nothing’s Gonna Change My Love For You",'Cover / 翻唱']];
export const copy={en:{work:'Work',resume:'Resume',contact:'Contact',welcome:'Make yourself at home.',role:'PRODUCT DESIGN / AI / PLAY',loading:'Opening the studio',failure:'The 3D studio could not load. Every project is still here.',ready:'',close:'Back to the room',overview:'That object is unavailable. Explore the room or browse the work.',finfold:'Finfold',music:'Music',books:'The bookshelf',about:'About',writing:'Notes',allwork:'Selected work',open:'Open case study',load:'Load player',external:'Open on NetEase',player:'Use the embedded controls to play. If the player is unavailable, open the track on NetEase.',stopped:'Player closed while you were away. Load it again to listen.',live:'Enter the live video',loadvideo:'Load the music video',booksbody:'A space for a real reading list. The books in this internal preview are neutral props; personal titles and notes are still to come.',aboutbody:'I’m Joey Zhao, a product designer working across enterprise software, AI products, and interactive experiences. Away from product work, I make music and visual experiments.',finfoldbody:'A growth digital employee for small teams: from a brief to research, creation, publishing, and review. Explore the product and design decisions in the full case study.',writingbody:'Notes on AI products, complex systems, and design judgment.',preview:'INTERNAL PREVIEW',video:'Use the video controls to start playback. If the embed is unavailable, open YouTube.',youtube:'Open on YouTube'},zh:{work:'作品',resume:'简历',contact:'联系',welcome:'随便看看，像在自己家一样。',role:'产品设计 / AI / 交互创作',loading:'工作室载入中',failure:'三维工作室未能加载。你仍可浏览所有作品。',ready:'',close:'回到工作室',overview:'这个物件暂不可用。可以继续探索或浏览作品。',finfold:'Finfold',music:'音乐',books:'书架',about:'关于我',writing:'笔记',allwork:'精选作品',open:'查看完整案例',load:'加载播放器',external:'在网易云打开',player:'请使用嵌入播放器控件开始播放；如果不可用，可在网易云打开歌曲。',stopped:'离开页面时已关闭播放器。可重新加载继续收听。',live:'进入现场影像',loadvideo:'加载音乐视频',booksbody:'这里留给真实的阅读收藏。内部预览中的书本仅为中性道具，书名与个人感受仍待补充。',aboutbody:'我是赵越，一名产品设计师，关注企业软件、AI 产品与交互体验。产品工作之外，我也创作音乐和影像。',finfoldbody:'面向小团队的增长数字员工：从目标出发，完成研究、创作、发布与复盘。完整案例展示产品与设计决策。',writingbody:'关于 AI 产品、复杂系统和设计判断的笔记。',preview:'内部预览',video:'请使用视频控件开始播放。如果无法加载，可在 YouTube 打开。',youtube:'在 YouTube 打开'}};
// Dates and titles match the published articles' BlogPosting metadata.
export const writing=[
 {slug:'neon-dream-ai-music-notes',date:'2026-08-30',en:'How I Made Neon Dream with AI',zh:'我怎样用 AI 做出《霓虹梦境》'},
 {slug:'silk-circuit-ai-music-notes',date:'2026-08-30',en:'Connecting Eastern Sound to Silk Circuit',zh:'把东方声音接进《丝电回路》'},
 {slug:'seven-eleven-layout-psychology',date:'2026-08-16',en:'The 7-Eleven Layout: How a 30㎡ Store Gets You to Buy Three Extra Things',zh:'7-11 只有 30㎡，凭什么让你每次多买三样？'},
 {slug:'starbucks-cup-perceived-value',date:'2026-08-16',en:'Starbucks Cup Design: How a Paper Cup Convinces You the Price Is Fine',zh:'星巴克的杯子，是怎么说服你「40 块不贵」的？'},
 {slug:'apple-store-invisible-door',date:'2026-07-14',en:'Where Did the Apple Store’s Door Go? The Trade-off Behind an Invisible Door',zh:'苹果店的门去哪了？一扇「看不见的门」背后的设计取舍'}
];
export function writingPath(slug,language){if(!writing.some(article=>article.slug===slug))return language==='zh'?'/writing/':'/en/writing/';return `${language==='zh'?'':'/en'}/writing/${slug}`;}
export function contactPath(kind,language){const subjects={recruiting:{en:'Design role opportunity — Joey Zhao',zh:'设计岗位沟通 — 赵越'},project:{en:'Project collaboration — Joey Zhao',zh:'项目合作 — 赵越'}};return 'mailto:super666joey@gmail.com?subject='+encodeURIComponent(subjects[kind==='recruiting'?'recruiting':'project'][language==='zh'?'zh':'en']);}
export function resumePath(language){return language==='zh'?'/resume/赵越-高级AI产品设计师-简历.pdf':'/resume/Yue-Zhao-Senior-AI-Product-Designer-Resume.pdf';}
Object.assign(copy.en,{recruiting:'Discuss a design role',project:'Discuss a project',problem:'THE PROBLEM',roleLabel:'MY ROLE',decisions:'DESIGN DECISIONS',finfoldProblem:'Small teams rewrite the same product update for each platform, then compare, edit, and save the results across tabs. The work extends beyond generating text.',finfoldRole:'Product lead: problem framing, research structure, information architecture, interaction design, and the design system, with implementation and release verification.',finfoldDecisions:'A three-step workbench keeps source material, platform selection, and content kits together. Brand memory and rules guide generation. On mobile, the denser desktop workspace becomes a sequential flow.',evidence:'Based on the published case study; this preview makes no outcome claims.',product:'Open the product workbench'});
Object.assign(copy.zh,{recruiting:'聊聊设计岗位',project:'聊聊项目合作',problem:'具体问题',roleLabel:'我的职责',decisions:'设计决策',finfoldProblem:'小团队需要为不同平台反复改写同一条产品更新，再跨标签页比较、编辑和保存。生成文字只是其中一步。',finfoldRole:'作为产品负责人，负责问题定义、研究框架、信息架构、交互与设计系统，并跟进实现和发布验证。',finfoldDecisions:'用三步工作台串起原始素材、平台选择和内容包；让品牌记忆与规则进入生成路径。桌面信息密度较高，手机端改为顺序操作流程。',evidence:'以上来自已发表案例；此预览不声称未经验证的成果。',product:'打开产品工作台'});

Object.assign(copy.en,{booksPreview:"Bookshelf",around:"IN THE STUDIO"});
Object.assign(copy.zh,{booksPreview:"书架",around:"工作室"});

Object.assign(copy.en,{classicExit:"Classic"});
Object.assign(copy.zh,{classicExit:"经典版"});

Object.assign(copy.en,{modeExplore:"EXPLORE",modeClassic:"CLASSIC",browseClassic:"Browse Classic",skip:"Skip to navigation",title:"Joey Zhao | AI Product Designer — Interactive Studio",viewToggle:"Portfolio view",loadingNav:"Explore studio content",hotspotsLabel:"Objects in the studio"});
Object.assign(copy.zh,{modeExplore:"探索",modeClassic:"经典",browseClassic:"浏览经典版",skip:"跳到导航",title:"Joey Zhao 赵越 | AI 产品设计师 — 互动工作室",viewToggle:"作品集视图",loadingNav:"探索工作室内容",hotspotsLabel:"工作室里的物件"});
Object.assign(copy.en,{photography:'Photography',photographyFull:'View the photography portfolio',photoUnavailable:'This photograph could not load.',previous:'Previous photograph',next:'Next photograph',writingFull:'All writing',featured:'FEATURED WORK',otherWork:'MORE PROJECTS'});
Object.assign(copy.zh,{photography:'摄影',photographyFull:'浏览完整摄影作品',photoUnavailable:'照片暂时无法载入。',previous:'上一张照片',next:'下一张照片',writingFull:'全部文章',featured:'精选作品',otherWork:'更多项目'});
export const featuredWork=[
 {title:'Signals Notebook',path:'/signals',image:'/images/signals-cover.jpg',role:{en:'Senior Product Designer',zh:'高级产品设计师'},summary:{en:'Designed the scientific data lineage workflow, from research synthesis and interaction model through usability checks and engineering handoff.',zh:'负责科研数据脉络流程的设计，从研究整理与交互模型，到可用性检验和研发交付。'}},
 {title:'Finfold',path:'/finfold',image:'/images/finfold-hero-landing.png',role:{en:'Product Lead',zh:'产品负责人'},summary:{en:'Led product definition, research, information architecture, interaction design, and the design system for an AI growth workspace.',zh:'负责 AI 增长工作台的产品定义、研究、信息架构、交互与设计系统。'}},
 {title:'ID.AURA',path:'/vw-id-aura/',image:'/vw-id-aura/assets/og-cover.jpg',role:{en:'Design & build',zh:'设计与实现'},summary:{en:'Designed and built a Volkswagen electric vehicle HMI concept with showroom, cluster, console, and autonomous modes.',zh:'设计并实现大众电动车 HMI 概念，串联展厅、仪表、控制台与自动驾驶四种模式。'}}
];

Object.assign(copy.en,{music:'Music by Joey',games:'Games by Joey'});
Object.assign(copy.zh,{music:'我的音乐创作',games:'我的游戏'});
Object.assign(copy.en,{discoveryTitle:'STUDIO DETAILS',discoveryHint:'Find the marked objects around the room. Each keeps a small story.',discoveryHidden:'An unseen detail',discovery_monitor:'A light behind the monitor',discovery_arcade:'A playable arcade cabinet',discovery_record:'The record waiting on its player',discovery_books:'A quiet corner of the bookshelf',discovery_portrait:'The maker at the desk',discovery_photography:'A frame on the photo wall',rewardIntro:'You found every detail. This after-hours studio picture is yours to keep in this browser.',guestbookTitle:'A note to this room',guestbookPrivate:'This note stays private on this device. It is not posted or visible to Joey or other visitors.',guestbookPlaceholder:'Leave a thought for yourself…',guestbookSave:'Save on this device',guestbookSaved:'Saved on this device.',guestbookFailed:'This browser could not save the note.',gameFailed:'The game could not load.',gameRetry:'Try loading again'});
Object.assign(copy.zh,{discoveryTitle:'工作室细节',discoveryHint:'寻找房间里的物件，每件都藏着一点故事。',discoveryHidden:'尚未发现的细节',discovery_monitor:'显示器背后的光',discovery_arcade:'可以游玩的街机',discovery_record:'唱机上的那张唱片',discovery_books:'书架安静的一角',discovery_portrait:'伏案创作的人',discovery_photography:'照片墙上的一帧',rewardIntro:'所有细节都找到了。这张深夜工作室画面会留在你的浏览器里。',guestbookTitle:'留给这间房的一句话',guestbookPrivate:'这条便签只保存在当前设备，不会发布，赵越和其他访客也看不到。',guestbookPlaceholder:'留一句话给自己……',guestbookSave:'保存在本机',guestbookSaved:'已保存在本机。',guestbookFailed:'浏览器未能保存便签。',gameFailed:'游戏暂时无法载入。',gameRetry:'重试载入'});
Object.assign(copy.en,{discoveryHint:'Explore the monitor, arcade, record, bookshelf, portrait and photo wall to reveal this room’s details.'});
Object.assign(copy.zh,{discoveryHint:'探索显示器、街机、唱片、书架、人物和照片墙，收集房间里的细节。'});
Object.assign(copy.en,{detailMonitor:'Inspect the monitor edge',detailRecord:'Turn the record sleeve',detailBooks:'Trace a book spine',detailLamp:'Tap the desk lamp',detailPhoto:'Look behind this frame',detailAgain:'Something shifted. Try again.',gameIntro:'Move the frame. Catch the city lights before they fade.',gameStart:'Start 45-second round',gameRestart:'Play again',gameKeys:'Arrow keys / WASD to move · Space or tap to capture',gameTime:'TIME',gameScore:'SCORE',gameBest:'BEST',gameEnd:'Exposure complete',gamePaused:'Paused while this tab is hidden',gameCaught:'Light captured',gameMissed:'Find a light inside the frame',gameCanvas:'Pixel Framing playfield'});
Object.assign(copy.zh,{detailMonitor:'看看显示器边缘',detailRecord:'翻转唱片封套',detailBooks:'沿着书脊摸一摸',detailLamp:'轻点台灯',detailPhoto:'看看画框背后',detailAgain:'有一点变化，再试一次。',gameIntro:'移动取景框，捕捉消逝前的城市灯光。',gameStart:'开始 45 秒挑战',gameRestart:'再玩一次',gameKeys:'方向键 / WASD 移动 · 空格键或点击捕捉',gameTime:'剩余',gameScore:'得分',gameBest:'最高',gameEnd:'曝光完成',gamePaused:'切到其他页面时已暂停',gameCaught:'捕捉成功',gameMissed:'把灯光放进取景框',gameCanvas:'像素取景游戏画面'});
Object.assign(copy.en,{gameCapture:'Capture'});
Object.assign(copy.zh,{gameCapture:'拍摄'});
Object.assign(copy.en,{gameTitle:'PIXEL FRAMING'});
Object.assign(copy.zh,{gameTitle:'像素取景'});
