// Public content and routes sourced from the existing Classic portfolio.
export const projects=[['Finfold','/finfold'],['Signals Notebook','/signals'],['CollovGPT','/collov'],['Ctrip Hotel','/ctrip'],['UnifyUX','/unifyux'],['ID.AURA','/vw-id-aura/'],['CALL ME YAO 妖','/yao'],['Bill Vampire','/billvampire'],['WeNeed','/weneed'],['Crypto Copilot','/cryptocopilot'],['Narrative Card RPG','/pleasurecontract'],['Borrowed Light','/borrowedlight']];
export const tracks=[['3428817825','霓虹梦境 · Neon Dream','Original / 原创'],['3428818648','丝电回路 · Silk Circuit','Original / 原创'],['3413956825','招安不是上岸','2026'],['3413978040','사상 최고가의 여름','2026'],['1873346292','逍遥叹','Cover / 翻唱'],['1969608391','Right Here Waiting For You','Cover / 翻唱'],['2746338489',"Nothing’s Gonna Change My Love For You",'Cover / 翻唱']];
export const copy={en:{work:'Work',resume:'Resume',contact:'Contact',welcome:'Make yourself at home.',role:'PRODUCT DESIGN / AI / PLAY',loading:'Opening the studio…',failure:'The 3D studio could not load. Every project is still here.',ready:'Choose something that catches your eye.',close:'Back to the room',overview:'That object is unavailable. Explore the room or browse the work.',finfold:'Finfold',music:'The listening corner',books:'On the bookshelf',about:'A little about me',writing:'Notes from the desk',allwork:'Selected work',open:'Open case study',load:'Load player',external:'Open on NetEase',player:'Use the embedded controls to play. If the player is unavailable, open the track on NetEase.',stopped:'Player closed while you were away. Load it again to listen.',live:'Enter the live video',loadvideo:'Load the music video',booksbody:'A space for a real reading list. The books in this internal preview are neutral props; personal titles and notes are still to come.',aboutbody:'I’m Joey Zhao, a product designer working across enterprise software, AI products, and interactive experiences. Away from product work, I make music and visual experiments.',finfoldbody:'A growth digital employee for small teams: from a brief to research, creation, publishing, and review. Explore the product and design decisions in the full case study.',writingbody:'Notes on AI products, complex systems, and design judgment.',preview:'INTERNAL PREVIEW',video:'Use the video controls to start playback. If the embed is unavailable, open YouTube.',youtube:'Open on YouTube'},zh:{work:'作品',resume:'简历',contact:'联系',welcome:'随便看看，像在自己家一样。',role:'产品设计 / AI / 交互创作',loading:'正在打开工作室…',failure:'三维工作室未能加载。你仍可浏览所有作品。',ready:'点开一件让你好奇的东西。',close:'回到工作室',overview:'这个物件暂不可用。可以继续探索或浏览作品。',finfold:'Finfold',music:'听听音乐',books:'书架上的留白',about:'关于我',writing:'桌边笔记',allwork:'作品目录',open:'查看完整案例',load:'加载播放器',external:'在网易云打开',player:'请使用嵌入播放器控件开始播放；如果不可用，可在网易云打开歌曲。',stopped:'离开页面时已关闭播放器。可重新加载继续收听。',live:'进入现场影像',loadvideo:'加载音乐视频',booksbody:'这里留给真实的阅读收藏。内部预览中的书本仅为中性道具，书名与个人感受仍待补充。',aboutbody:'我是赵越，一名产品设计师，关注企业软件、AI 产品与交互体验。产品工作之外，我也创作音乐和影像。',finfoldbody:'面向小团队的增长数字员工：从目标出发，完成研究、创作、发布与复盘。完整案例展示产品与设计决策。',writingbody:'关于 AI 产品、复杂系统和设计判断的笔记。',preview:'内部预览',video:'请使用视频控件开始播放。如果无法加载，可在 YouTube 打开。',youtube:'在 YouTube 打开'}};
export const writing=[{slug:'ai-designers-cannot-only-sell-screens',en:'Designing AI Agents Beyond the Screen',zh:'做 AI Agent，别只画页面'},{slug:'mcdonalds-seating-business-tradeoffs',en:'What Is McDonald’s Seating Really Optimizing?',zh:'麦当劳的座椅，究竟在优化什么？'},{slug:'finfold-one-brief-eleven-platforms',en:'From One Brief to 14 Platforms',zh:'从一个 Brief 到 14 个平台'}];
export function writingPath(slug,language){if(!writing.some(article=>article.slug===slug))return language==='zh'?'/writing/':'/en/writing/';return `${language==='zh'?'':'/en'}/writing/${slug}`;}
export function contactPath(kind,language){const subjects={recruiting:{en:'Design role opportunity — Joey Zhao',zh:'设计岗位沟通 — 赵越'},project:{en:'Project collaboration — Joey Zhao',zh:'项目合作 — 赵越'}};return 'mailto:super666joey@gmail.com?subject='+encodeURIComponent(subjects[kind==='recruiting'?'recruiting':'project'][language==='zh'?'zh':'en']);}
Object.assign(copy.en,{recruiting:'Discuss a design role',project:'Discuss a project',problem:'THE PROBLEM',roleLabel:'MY ROLE',decisions:'DESIGN DECISIONS',finfoldProblem:'Small teams rewrite the same product update for each platform, then compare, edit, and save the results across tabs. The work extends beyond generating text.',finfoldRole:'Product lead: problem framing, research structure, information architecture, interaction design, and the design system, with implementation and release verification.',finfoldDecisions:'A three-step workbench keeps source material, platform selection, and content kits together. Brand memory and rules guide generation. On mobile, the denser desktop workspace becomes a sequential flow.',evidence:'Based on the published case study; this preview makes no outcome claims.',product:'Open the product workbench'});
Object.assign(copy.zh,{recruiting:'聊聊设计岗位',project:'聊聊项目合作',problem:'具体问题',roleLabel:'我的职责',decisions:'设计决策',finfoldProblem:'小团队需要为不同平台反复改写同一条产品更新，再跨标签页比较、编辑和保存。生成文字只是其中一步。',finfoldRole:'作为产品负责人，负责问题定义、研究框架、信息架构、交互与设计系统，并跟进实现和发布验证。',finfoldDecisions:'用三步工作台串起原始素材、平台选择和内容包；让品牌记忆与规则进入生成路径。桌面信息密度较高，手机端改为顺序操作流程。',evidence:'以上来自已发表案例；此预览不声称未经验证的成果。',product:'打开产品工作台'});

Object.assign(copy.en,{booksPreview:"Bookshelf",around:"AROUND THE STUDIO"});
Object.assign(copy.zh,{booksPreview:"书架",around:"工作室里的其他角落"});

Object.assign(copy.en,{classicExit:"Classic ↗"});
Object.assign(copy.zh,{classicExit:"经典版 ↗"});
