const base='/explore/assets/photography/';
export const photography=Object.freeze([
 {id:'p05_img1',source:'https://photography-portfolio-rd5.pages.dev/images/p05_img1.jpeg',width:4096,height:2731,en:'Portraits',zh:'人像',altEn:'Black and white portrait of a woman in a white dress and broad-brimmed hat.',altZh:'黑白肖像：一位穿白裙、戴宽檐帽的女性。'},
 {id:'p11_img1',source:'https://photography-portfolio-rd5.pages.dev/images/p11_img1.jpeg',width:4096,height:2734,en:'Belgium',zh:'比利时',altEn:'Historic gabled buildings and a clock tower reflected in a canal at dusk.',altZh:'黄昏时，山墙建筑与钟楼倒映在运河中。'},
 {id:'p07_img1',source:'https://photography-portfolio-rd5.pages.dev/images/p07_img1.jpeg',width:4096,height:2731,en:'Portraits',zh:'人像',altEn:'Portrait of a woman in white holding blue flowers against a pale background.',altZh:'浅色背景前，一位身穿白衣的女性手持蓝色花束。'},
 {id:'p12_img1',source:'https://photography-portfolio-rd5.pages.dev/images/p12_img1.jpeg',width:4096,height:2734,en:'Turkey',zh:'土耳其',altEn:'A wide view of stone buildings and rock formations beneath an overcast sky.',altZh:'阴云下的石砌城镇与岩石地貌。'},
 {id:'p13_img1',source:'https://photography-portfolio-rd5.pages.dev/images/p13_img1.jpeg',width:4096,height:2734,en:'Casa Batlló, Barcelona',zh:'巴特罗之家，巴塞罗那',altEn:'A golden circular ceiling light beneath a swirling sculptural vault.',altZh:'金色圆形灯具悬于旋转形态的穹顶下。'},
 {id:'usa_ride2',source:'local:Documents/photography/2025.10 USA/DSC04823.JPG',width:7008,height:4672,en:'Horseback Riding, USA',zh:'骑马 · 美国',altEn:'A rider trots a chestnut horse across open sagebrush flats beneath distant mountains.',altZh:'骑手策马小跑，穿过灌木草原，远处是连绵山脉。'},
 {id:'p13_img2',source:'https://photography-portfolio-rd5.pages.dev/images/p13_img2.jpeg',width:4096,height:2734,en:'Casa Batlló, Barcelona',zh:'巴特罗之家，巴塞罗那',altEn:'Sculptural chimneys of Casa Batlló against a deep blue sky.',altZh:'深蓝天空下，巴特罗之家雕塑般的烟囱。'},
 {id:'p18_img1',source:'https://photography-portfolio-rd5.pages.dev/images/p18_img1.jpeg',width:1627,height:1030,en:'AC Milan vs Roma',zh:'AC 米兰对罗马',altEn:'Two football players contest the ball on a vivid green pitch.',altZh:'鲜绿球场上，两位足球运动员争抢皮球。'}
].map(photo=>Object.freeze({...photo,display:`${base}${photo.id}.webp`,cover:`${base}${photo.id}-cover.webp`})));
