import {ROUND_MS,newRound,moveFrame,stepRound,captureLight} from './pixel-framing-rules.mjs?v=20260929-p2';
import {copy} from './content.mjs?v=20260929-p2fix1';
export function mountPixelFraming(host,language){const c=copy[language==='zh'?'zh':'en'],t={intro:c.gameIntro,start:c.gameStart,restart:c.gameRestart,keys:c.gameKeys,time:c.gameTime,score:c.gameScore,best:c.gameBest,end:c.gameEnd,paused:c.gamePaused,caught:c.gameCaught,missed:c.gameMissed};let state=null,raf=0,last=0,drag=false,disposed=false,best=0;try{best=Math.max(0,Number(localStorage.getItem('pixel-framing-best-v1'))||0)}catch{}
 const shell=document.createElement('section');shell.className='pixel-game';shell.innerHTML='<div class="pixel-game-head"><span>PIXEL FRAMING / 像素取景</span><span class="pixel-game-stats"></span></div><canvas width="640" height="380" aria-label="Pixel Framing playfield"></canvas><p class="pixel-game-message" aria-live="polite"></p><div class="pixel-game-actions"><button class="small-button pixel-start"></button><button class="small-button pixel-capture" hidden>◎</button></div><p class="pixel-game-hint"></p>';host.append(shell);
 const canvas=shell.querySelector('canvas'),ctx=canvas.getContext('2d'),message=shell.querySelector('.pixel-game-message'),stats=shell.querySelector('.pixel-game-stats'),start=shell.querySelector('.pixel-start'),capture=shell.querySelector('.pixel-capture');shell.querySelector('.pixel-game-head span').textContent=c.gameTitle;capture.textContent=c.gameCapture;capture.setAttribute('aria-label',c.gameCapture);shell.querySelector('.pixel-game-hint').textContent=t.keys;message.textContent=t.intro;start.textContent=t.start;stats.textContent=`${t.best} ${best}`;
 function draw(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#101824';ctx.fillRect(0,0,w,h);for(let i=0;i<24;i++){const x=(i*89)%w,height=45+(i*37)%125;ctx.fillStyle=i%3?'#1d2b39':'#26313c';ctx.fillRect(x,h-height,28+(i%4)*9,height);for(let j=0;j<4;j++){ctx.fillStyle='#c8aa73';ctx.globalAlpha=.13+(i+j)%3*.08;ctx.fillRect(x+7+j*10,h-height+16,3,5)}}ctx.globalAlpha=1;const s=state;if(!s)return;for(const light of s.lights){ctx.beginPath();ctx.arc(light.x*w,light.y*h,4+(1-light.age/1900)*7,0,Math.PI*2);ctx.fillStyle='#f5d99e';ctx.shadowBlur=20;ctx.shadowColor='#f0bd6d';ctx.fill();ctx.shadowBlur=0;}const x=s.x*w,y=s.y*h;ctx.strokeStyle='#e7d8b9';ctx.lineWidth=2;ctx.strokeRect(x-49,y-39,98,78);ctx.strokeStyle='#e7d8b966';ctx.beginPath();ctx.moveTo(x-8,y);ctx.lineTo(x+8,y);ctx.moveTo(x,y-8);ctx.lineTo(x,y+8);ctx.stroke();}
 function updateStats(){stats.textContent=`${t.time} ${Math.ceil((ROUND_MS-state.elapsed)/1000)}  ·  ${t.score} ${state.score}  ·  ${t.best} ${best}`;}
 function tick(now){raf=0;if(disposed||!state||state.finished||document.hidden)return;stepRound(state,now-last);last=now;draw();updateStats();if(state.finished){capture.hidden=true;start.hidden=false;start.textContent=t.restart;message.textContent=`${t.end} · ${state.score}`;if(state.score>best){best=state.score;try{localStorage.setItem('pixel-framing-best-v1',String(best))}catch{}}window.dispatchEvent(new CustomEvent('studio:game',{detail:{phase:'end',score:state.score}}));return}raf=requestAnimationFrame(tick)}
 function begin(){cancelAnimationFrame(raf);state=newRound(Date.now());start.hidden=true;capture.hidden=false;message.textContent=t.intro;last=performance.now();draw();updateStats();window.dispatchEvent(new CustomEvent('studio:game',{detail:{phase:'start'}}));raf=requestAnimationFrame(tick);canvas.focus({preventScroll:true})}
 function shoot(){if(!state||state.finished)return;const caught=captureLight(state);message.textContent=caught?t.caught:t.missed;if(caught)window.dispatchEvent(new CustomEvent('studio:game',{detail:{phase:'capture',score:state.score}}));draw();updateStats()}
 function key(event){if(!state||state.finished||document.activeElement!==canvas)return;const offset={ArrowLeft:[-.045,0],KeyA:[-.045,0],ArrowRight:[.045,0],KeyD:[.045,0],ArrowUp:[0,-.045],KeyW:[0,-.045],ArrowDown:[0,.045],KeyS:[0,.045]}[event.code];if(offset){event.preventDefault();moveFrame(state,state.x+offset[0],state.y+offset[1]);draw()}else if(event.code==='Space'){event.preventDefault();shoot()}}
 function pointer(event){if(!state||state.finished)return;const box=canvas.getBoundingClientRect();moveFrame(state,(event.clientX-box.left)/box.width,(event.clientY-box.top)/box.height);draw()}
 function visibility(){if(document.hidden){cancelAnimationFrame(raf);raf=0;if(state&&!state.finished)message.textContent=t.paused}else if(state&&!state.finished&&!raf){last=performance.now();raf=requestAnimationFrame(tick)}}
 canvas.setAttribute('aria-label',c.gameCanvas);canvas.tabIndex=0;start.addEventListener('click',begin);capture.addEventListener('click',shoot);canvas.addEventListener('pointerdown',event=>{drag=true;canvas.setPointerCapture(event.pointerId);pointer(event);shoot()});canvas.addEventListener('pointermove',event=>{if(drag)pointer(event)});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('keydown',key);document.addEventListener('visibilitychange',visibility);draw();
 return ()=>{disposed=true;cancelAnimationFrame(raf);document.removeEventListener('visibilitychange',visibility);shell.remove()};}
