import * as THREE from 'three';
import {moveView,viewOffset} from './camera-control.mjs';
let view={x:0,y:0};
function resetView(){view={x:0,y:0};cameraPose();}
window.addEventListener('studio:reset-view',resetView);
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from './vendor/meshopt_decoder.mjs';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const root=document.querySelector('#scene-root');
const emit=(name,detail={})=>window.dispatchEvent(new CustomEvent(name,{detail}));
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const anchors={finfold:[-.4443,1.25,1.3311],music:[-2,1,1.6],books:[-2.4,1.9,-2.05],about:[1.244,1.32,.177],work:[-3.43,1.96,-.58],writing:[.825,.85,.537]};
let renderer,scene,camera,raf=0,selected=null,disposed=false,sceneReady=false,contextLost=false,last=0,record=null,recordBaseY=0,tonearm=null,armBaseY=0,avatar=null,book=null,bookRest=null,bookRestRotation=0;
const typingMeshes=[];
const target=new THREE.Vector3(),desired=new THREE.Vector3(),look=new THREE.Vector3(),desiredLook=new THREE.Vector3();
const clock=new THREE.Clock();
let sampleStart=0,sampleFrames=0;
function cameraPose(){const mobile=root.clientWidth<700;desired.set(...(mobile?[.5,2,5.8]:[.1,1.7,4.6]));desiredLook.set(...(mobile?[.55,1.12,.6]:[-.1,1.1,.7]));if(root.dataset.reviewView){const views={side:[[3.8,1.6,.3],[.6,1,.65]],top:[[.6,5,.701],[.6,.8,.7]],hands:[[2.0,1.5,2.3],[.85,.86,.52]]};const v=views[root.dataset.reviewView];if(v){desired.set(...v[0]);desiredLook.set(...v[1]);}}if(!selected&&!root.dataset.reviewView){const offset=viewOffset(view,mobile);const orbit=new THREE.Spherical().setFromVector3(desired.clone().sub(desiredLook));orbit.theta+=offset.yaw;orbit.phi+=offset.pitch;desired.copy(desiredLook).add(new THREE.Vector3().setFromSpherical(orbit));root.dataset.viewX=view.x.toFixed(2);root.dataset.viewY=view.y.toFixed(2);}if(selected&&anchors[selected]){const a=new THREE.Vector3(...anchors[selected]);desired.lerp(a.clone().add(new THREE.Vector3(3,1.6,4)),.35);desiredLook.lerp(a,.32)}}
function resize(){if(!renderer)return;const w=root.clientWidth,h=root.clientHeight;camera.aspect=w/h;camera.fov=w<700?47:43;camera.updateProjectionMatrix();renderer.setSize(w,h,false);renderer.setPixelRatio(Math.min(devicePixelRatio,w<700?1.5:2));cameraPose();}
function lights(){scene.add(new THREE.HemisphereLight(0xa4bacb,0x30231a,.3));const key=new THREE.DirectionalLight(0xffd3a0,.65);key.position.set(-2,4,3);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:15});key.shadow.bias=-.00015;key.shadow.normalBias=.025;scene.add(key);const blue=new THREE.SpotLight(0x76b8ff,35,10,1.05,.85,2);blue.position.set(2,2.8,-2.1);blue.target.position.set(.2,.6,1);scene.add(blue,blue.target);const warm=new THREE.PointLight(0xffb75d,10,5,2);warm.position.set(-.95,1.52,1.45);scene.add(warm);const consoleGlow=new THREE.PointLight(0xffb76a,8,3,2);consoleGlow.position.set(-2.6,1.18,1.48);scene.add(consoleGlow);const shelfGlow=new THREE.PointLight(0xffb365,8,4,2);shelfGlow.position.set(-2.1,2,-1.85);scene.add(shelfGlow);}
function frame(ms=0){raf=0;if(disposed||contextLost||document.hidden)return;const dt=Math.min((ms-last)/1000||.016,.05);last=ms;const damping=reduced.matches?1:1-Math.exp(-dt*5);camera.position.lerp(desired,damping);look.lerp(desiredLook,damping);camera.lookAt(look);if(tonearm){const armOpen=selected==='music'||(record&&record.position.y-recordBaseY>.006);tonearm.rotation.y=THREE.MathUtils.lerp(tonearm.rotation.y,armOpen?.58:0,damping);tonearm.position.y=THREE.MathUtils.lerp(tonearm.position.y,armBaseY+(armOpen||tonearm.rotation.y>.02?.02:0),damping);}if(record){const lift=selected==='music'&&(!tonearm||tonearm.rotation.y>.3)?.12:0;record.position.y=THREE.MathUtils.lerp(record.position.y,recordBaseY+lift,damping);}if(book){book.position.z=THREE.MathUtils.lerp(book.position.z,bookRest.z+(selected==='books'?.22:0),damping);book.rotation.y=THREE.MathUtils.lerp(book.rotation.y,bookRestRotation+(selected==='books'?-.14:0),damping);}if(avatar){const t=clock.getElapsedTime();avatar.scale.y=reduced.matches?1:1+Math.sin(t*1.4)*.001;const active=!reduced.matches&&!selected;const cycle=t%7;const burst=active?Math.min(1,cycle/.4)*Math.max(0,Math.min(1,(4.8-cycle)/.6)):0;for(const hand of typingMeshes){hand.morphTargetInfluences[hand.morphTargetDictionary.Typing_Left]=burst*Math.pow(Math.max(0,Math.sin(t*19)),2);hand.morphTargetInfluences[hand.morphTargetDictionary.Typing_Right]=burst*Math.pow(Math.max(0,Math.sin(t*21+1.8)),2);root.dataset.typingLeft=hand.morphTargetInfluences[hand.morphTargetDictionary.Typing_Left].toFixed(3);root.dataset.typingRight=hand.morphTargetInfluences[hand.morphTargetDictionary.Typing_Right].toFixed(3);}}renderer.render(scene,camera);if(!root.dataset.firstFrameMs)root.dataset.firstFrameMs=Math.round(performance.now());if(!sampleStart)sampleStart=ms;sampleFrames++;if(ms-sampleStart>2000){root.dataset.sampleFps=(sampleFrames*1000/(ms-sampleStart)).toFixed(1);root.dataset.drawCalls=renderer.info.render.calls;root.dataset.triangles=renderer.info.render.triangles;sampleStart=ms;sampleFrames=0;}for(const [id,p] of Object.entries(anchors)){const button=document.querySelector(`[data-object="${id}"]`);if(!button)continue;target.set(...p).project(camera);button.hidden=target.z>1||Math.abs(target.x)>.96||Math.abs(target.y)>.86;button.style.left=`${(target.x*.5+.5)*root.clientWidth}px`;button.style.top=`${(-target.y*.5+.5)*root.clientHeight}px`;}raf=requestAnimationFrame(frame);}
function resume(){if(!raf&&!disposed&&!contextLost&&sceneReady){last=performance.now();raf=requestAnimationFrame(frame)}}
function stop(){cancelAnimationFrame(raf);raf=0;}
function dispose(){disposed=true;stop();scene?.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose()}});renderer?.dispose();}
window.addEventListener('studio:select',e=>{selected=e.detail?.id||null;view={x:0,y:0};cameraPose()});
document.addEventListener('visibilitychange',()=>document.hidden?stop():resume());window.addEventListener('pagehide',stop);window.addEventListener('pageshow',resume);window.addEventListener('resize',resize);
try{
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;root.append(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
 scene=new THREE.Scene();scene.background=new THREE.Color(0x171b20);camera=new THREE.PerspectiveCamera(43,1,.05,50);
 const pmrem=new THREE.PMREMGenerator(renderer);const env=new RoomEnvironment();scene.environment=pmrem.fromScene(env,.04).texture;env.dispose();pmrem.dispose();lights();resize();camera.position.copy(desired);look.copy(desiredLook);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;stop();emit('studio:failure')});renderer.domElement.addEventListener('webglcontextrestored',()=>location.reload());
 const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);const room=await loader.loadAsync('/explore/assets/room-packed.glb?v=desk7');scene.add(room.scene);const processed=new Set();room.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of Array.isArray(o.material)?o.material:[o.material]){if(processed.has(m))continue;processed.add(m);m.envMapIntensity=.22;if(m.name.includes("plaster"))m.color.multiplyScalar(.26);if(m.name.includes("stone"))m.color.multiplyScalar(.38);}}});

 // Extend the actual architectural shell beyond the authored furniture area.
 // The original room remains editable; these boxes avoid a cutaway silhouette.
 const plaster=[...processed].find(m=>m.name.includes('plaster'));
 const stone=[...processed].find(m=>m.name.includes('stone'));
 function shell(name,size,position,material){const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),material);mesh.name=name;mesh.position.set(...position);mesh.receiveShadow=true;scene.add(mesh);}
 shell('Continuous floor',[18,.16,18],[0,-.091,1],stone);
 shell('Left wall continuation',[.15,7,7.45],[-3.58,3.5,5.275],plaster);
 shell('Left upper wall',[.15,3.4,4.1],[-3.58,5.3,-.5],plaster);
 shell('Upper rear wall',[7.2,3.4,.15],[0,5.3,-2.5],plaster);
 shell('Rear right continuation',[5.5,7,.15],[6.25,3.5,-2.5],plaster);
 // A restrained fictional skyline behind the existing fluted glazing.
 const skyline=document.createElement('canvas');skyline.width=512;skyline.height=768;const city=skyline.getContext('2d');
 const sky=city.createLinearGradient(0,0,0,768);sky.addColorStop(0,'#101f32');sky.addColorStop(1,'#273949');city.fillStyle=sky;city.fillRect(0,0,512,768);
 let seed=72;const random=()=>((seed=(seed*16807)%2147483647)-1)/2147483646;
 for(let x=-25;x<512;){const width=45+random()*65,top=90+random()*260;city.fillStyle=random()>.5?'#101923':'#16222d';city.fillRect(x,top,width,768-top);for(let wx=x+9;wx<x+width-5;wx+=12)for(let wy=top+14;wy<768;wy+=23){if(random()>.46){city.fillStyle=random()>.3?'#a39674':'#68889f';city.globalAlpha=.25+random()*.5;city.fillRect(wx,wy,4,8);}}city.globalAlpha=1;x+=width+8;}
 const skylineTexture=new THREE.CanvasTexture(skyline);skylineTexture.colorSpace=THREE.SRGBColorSpace;const skylineMesh=new THREE.Mesh(new THREE.PlaneGeometry(2.76,3.13),new THREE.MeshBasicMaterial({map:skylineTexture,color:0x8195a5}));skylineMesh.position.set(2.02,1.96,-2.458);scene.add(skylineMesh);
 book=room.scene.getObjectByName('book_01');if(book){bookRest=book.position.clone();bookRestRotation=book.rotation.y;const center=new THREE.Box3().setFromObject(book).getCenter(new THREE.Vector3());anchors.books=center.toArray();}
 const turntable=await loader.loadAsync('/explore/assets/turntable-packed.glb');turntable.scene.position.set(-1.96,.855,1.61);turntable.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.item='music';}});scene.add(turntable.scene);// Compression can shift mesh origins. Restore the authored mechanical pivots.
 function pivot(name,position){const mesh=turntable.scene.getObjectByName(name);if(!mesh)return null;const group=new THREE.Group();group.name=name+'_pivot';group.position.set(...position);mesh.parent.add(group);group.updateWorldMatrix(true,false);group.attach(mesh);return group;}
 record=pivot('record_disc',[-.075,.133,.012]);recordBaseY=record?.position.y||0;tonearm=pivot('tonearm',[.272,.143,-.164]);armBaseY=tonearm?.position.y||0;
 const person=await loader.loadAsync(root.clientWidth<700?'/explore/assets/avatar-v2-mobile-packed.glb?v=pose4-final':'/explore/assets/avatar-v2-packed.glb?v=pose4-final');avatar=person.scene;avatar.position.set(1.244,.5976,.177);avatar.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.item='about';if(o.morphTargetDictionary?.Typing_Left!==undefined)typingMeshes.push(o);for(const m of Array.isArray(o.material)?o.material:[o.material])m.envMapIntensity=.35;}});scene.add(avatar);
 const screen=room.scene.getObjectByName('monitor_screen');if(screen){anchors.finfold=new THREE.Box3().setFromObject(screen).getCenter(new THREE.Vector3()).toArray();const texture=await new THREE.TextureLoader().loadAsync('/images/finfold-app-workbench.png');texture.colorSpace=THREE.SRGBColorSpace;texture.flipY=false;screen.material=new THREE.MeshBasicMaterial({map:texture});}
 for(const [url,z] of [['/images/yao-cover.jpg',-1.46],['/images/signals-cover.jpg',-.58]]){const texture=await new THREE.TextureLoader().loadAsync(url);texture.colorSpace=THREE.SRGBColorSpace;const ratio=texture.image.width/texture.image.height;const w=Math.min(.65,1.08*ratio),h=w/ratio;const art=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshStandardMaterial({map:texture,roughness:.85,envMapIntensity:.1}));art.name='project_artwork';art.rotation.y=Math.PI/2;art.position.set(-3.44,1.96,z);scene.add(art);}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;
 const canvas=renderer.domElement;
 canvas.tabIndex=0;canvas.removeAttribute('aria-hidden');canvas.setAttribute('role','region');
 const label=()=>canvas.setAttribute('aria-label',document.documentElement.lang==='zh'?'工作室视角：拖动或方向键环视，Home 键复位':'Studio view: drag or use arrow keys to look around; Home resets');label();window.addEventListener('studio:language',label);
 canvas.addEventListener('pointerdown',e=>{if(selected||e.button!==0||down)return;down={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging');});
 canvas.addEventListener('pointermove',e=>{if(!down||e.pointerId!==down.id)return;if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)down.moved=true;if(down.moved){view=moveView(view,-(e.clientX-down.lastX)/root.clientWidth*3,-(e.clientY-down.lastY)/root.clientHeight*3);cameraPose();}down.lastX=e.clientX;down.lastY=e.clientY;});
 const release=()=>{if(down&&canvas.hasPointerCapture(down.id))canvas.releasePointerCapture(down.id);down=null;canvas.classList.remove('dragging');};
 canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',()=>{down=null;canvas.classList.remove('dragging');});
 canvas.addEventListener('pointerup',e=>{if(!down||e.pointerId!==down.id)return;const moved=down.moved;release();if(moved||selected)return;const r=root.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(scene.children,true)[0];if(!hit)return;const n=hit.object.name.toLowerCase();const id=hit.object.userData.item|| (n.includes('monitor')?'finfold':n.includes('book')?'books':n.includes('record')?'music':n.includes('avatar')?'about':n.includes('artwork')?'work':null);if(id)emit('studio:pick',{id});});
 canvas.addEventListener('keydown',e=>{if(selected)return;const step={ArrowLeft:[-.18,0],ArrowRight:[.18,0],ArrowUp:[0,-.18],ArrowDown:[0,.18]}[e.key];if(step){e.preventDefault();view=moveView(view,...step);cameraPose();}else if(e.key==='Home'){e.preventDefault();resetView();}});
 if(!contextLost){root.dataset.interactiveMs=Math.round(performance.now());performance.mark('studio-interactive');sceneReady=true;emit('studio:ready');resume();}
}catch(error){console.error('Studio unavailable',error);dispose();emit('studio:failure');}
