import {collectionShelf} from './collections.mjs?v=links-v2';
import {parseLocation,buildLocation,resolveLanguage,validId} from './state.mjs';
import {copy,projects,tracks,writing,writingPath,contactPath} from './content.mjs';
const dialog=document.querySelector('#content-panel'),content=document.querySelector('#panel-content'),status=document.querySelector('#scene-status');
let saved;try{saved=localStorage.getItem('lang')}catch{}
let state=parseLocation(location.href),language=resolveLanguage(state.language,saved),selected=null,returnFocus=null,sceneState='loading';
const t=key=>copy[language][key];
const emit=(name,detail)=>window.dispatchEvent(new CustomEvent(name,{detail}));
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n};
function link(text,href,cls='panel-link'){const a=el('a',text,cls);a.href=href;if(href.startsWith('https:')){a.target='_blank';a.rel='noopener noreferrer'}return a}
function image(src,alt,cls='cover'){const img=el('img',null,cls);img.src=src;img.alt=alt;img.loading='lazy';return img}
function disposeMedia(){content.querySelectorAll('iframe').forEach(frame=>frame.remove())}
function player(type,id){disposeMedia();const box=content.querySelector('#media-player');box.replaceChildren();const frame=el('iframe');frame.title=type==='video'?'CALL ME YAO music video':'NetEase Cloud Music player';frame.allow='fullscreen; encrypted-media';frame.referrerPolicy='strict-origin-when-cross-origin';if(type==='video'){frame.src='https://www.youtube-nocookie.com/embed/FXCQGqpYmto';frame.className='video-player';frame.allowFullscreen=true}else{frame.src=`https://music.163.com/outchain/player?type=2&id=${id}&auto=0&height=66`;frame.height='100'}box.append(frame,el('p',t(type==='video'?'video':'player'),'media-status'));}
function appendContacts(){const row=el('div',null,'contact-actions');row.append(link(t('recruiting'),contactPath('recruiting',language)),link(t('project'),contactPath('project',language)));content.append(row)}
function render(){dialog.dataset.collection=['books','music'].includes(selected)?selected:'';disposeMedia();content.replaceChildren();const heading=el('h1',t(selected==='work'?'allwork':selected));heading.id='panel-title';content.append(heading);
 if(selected==='finfold'){content.append(image('/images/finfold-app-workbench.png','Finfold product workbench'));for(const [label,body] of [['problem','finfoldProblem'],['roleLabel','finfoldRole'],['decisions','finfoldDecisions']])content.append(el('h2',t(label),'eyebrow'),el('p',t(body)));content.append(link(t('open'),'/finfold'),link(t('product'),'https://www.finfold.app/workbench'));appendContacts();}
 if(selected==='about'){content.append(image('/explore/assets/portrait.png','Joey Zhao','portrait'),el('p',t('aboutbody')),link(t('resume'),'/resume/joey-zhao-resume.pdf'),link(t('contact'),'mailto:super666joey@gmail.com'));appendContacts();}
 if(selected==='work'){content.append(el('h2',t('around'),'eyebrow'));const objects=el('nav',null,'object-navigation');objects.setAttribute('aria-label',t('around'));for(const id of ['music','about','writing','books']){const button=el('button',t(id==='books'?'booksPreview':id),'small-button');button.dataset.open=id;objects.append(button)}content.append(objects);const list=el('ul',null,'project-list');for(const [title,path] of projects){const li=el('li');li.append(link(title,path,''));list.append(li)}content.append(list);}
 if(selected==='books'){content.append(collectionShelf('books',language));}
 if(selected==='writing'){content.append(el('p',t('writingbody')));for(const article of writing)content.append(link(article[language],writingPath(article.slug,language)));}
 if(selected==='music'){content.append(collectionShelf('albums',language));content.append(el('h2',language==='zh'?'Joey 的音乐与 MV':'Joey’s music & MV','eyebrow'));const media=el('div');media.id='media-player';content.append(media);const list=el('ul',null,'track-list');for(const [id,name,meta] of tracks){const li=el('li');li.append(el('span',name,'track-name'),el('div',meta,'track-meta'));const button=el('button',t('load'),'small-button');button.setAttribute('aria-label',`${t('load')}: ${name}`);button.addEventListener('click',()=>player('music',id));li.append(button,link(t('external'),`https://music.163.com/song?id=${id}`,''));list.append(li)}content.append(list,image('/images/yao-cover.jpg','CALL ME YAO music video'));const video=el('button',t('loadvideo'),'small-button');video.addEventListener('click',()=>{player('video');content.querySelector('#media-player').scrollIntoView({block:'nearest'});});content.append(video,link(t('youtube'),'https://www.youtube.com/watch?v=FXCQGqpYmto'),link(t('open'),'/yao'));}
}
function syncLanguage(){document.documentElement.lang=language;document.querySelectorAll('[data-copy]').forEach(n=>n.textContent=t(n.dataset.copy));document.querySelector('#language').textContent=language==='en'?'EN / 中文':'中文 / EN';document.querySelector('#language').setAttribute('aria-label',language==='en'?'Switch to Chinese':'切换为英语');document.querySelector('#panel-close').setAttribute('aria-label',t('close'));for(const b of document.querySelectorAll('[data-object]')){const key=b.dataset.object;const label=t(key==='work'?'allwork':key);b.setAttribute('aria-label',label);b.querySelector('span').textContent=label}status.textContent=t(sceneState);emit('studio:language',{language});}
function select(id,{historyMode='push',trigger=null}={}){id=validId(id);if(id===selected)return;if(!dialog.open)returnFocus=trigger||document.activeElement;selected=id;disposeMedia();if(historyMode==='push'){history.pushState({studio:true},'',buildLocation(location.href,id,language));}if(id){render();if(!dialog.open)dialog.showModal();document.querySelector('#panel-close').focus()}else{if(dialog.open)dialog.close();if(returnFocus?.isConnected&&returnFocus.getClientRects().length)returnFocus.focus();else document.querySelector('#studio-navigation [data-open=work]').focus();}emit('studio:select',{id});}
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-open]');if(trigger){event.preventDefault();select(trigger.dataset.open,{trigger});}const mode=event.target.closest('[data-mode]');if(mode){disposeMedia();try{localStorage.setItem('portfolio-mode',mode.dataset.mode)}catch{}}});
document.querySelector('#panel-close').addEventListener('click',()=>select(null));dialog.addEventListener('cancel',event=>{event.preventDefault();select(null)});dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)select(null)}});
document.querySelector('#language').addEventListener('click',()=>{language=language==='en'?'zh':'en';try{localStorage.setItem('lang',language)}catch{}history.replaceState(history.state,'',buildLocation(location.href,selected,language));syncLanguage();if(selected)render();});
window.addEventListener('popstate',()=>{const next=parseLocation(location.href);language=resolveLanguage(next.language,language);syncLanguage();if(next.id===selected&&selected)render();else select(next.id,{historyMode:'none'});if(next.invalidItem)status.textContent=t('overview');});
window.addEventListener('studio:pick',e=>select(e.detail?.id));window.addEventListener('studio:ready',()=>{sceneState='ready';document.body.dataset.sceneState=sceneState;status.textContent=t(sceneState);emit('studio:select',{id:selected})});window.addEventListener('studio:failure',()=>{sceneState='failure';document.body.dataset.sceneState=sceneState;status.textContent=t(sceneState)});
document.addEventListener('visibilitychange',()=>{if(document.hidden){const hadPlayer=!!content.querySelector('iframe');disposeMedia();if(hadPlayer){const box=content.querySelector('#media-player');box?.replaceChildren(el('p',t('stopped'),'media-status'))}}});window.addEventListener('pagehide',disposeMedia);
syncLanguage();if(state.id)select(state.id,{historyMode:'none'});if(state.invalidItem)status.textContent=t('overview');

const resetViewButton=document.querySelector('#view-reset');resetViewButton.addEventListener('click',()=>emit('studio:reset-view',{}));
function viewLabels(){const zh=language==='zh';document.querySelector('#view-hint').textContent=zh?'拖动环视 · 方向键微调':'Drag to explore · arrow keys';resetViewButton.textContent=zh?'回到初始视角 ↺':'Reset view ↺';}
window.addEventListener('studio:language',viewLabels);viewLabels();
